// <auto-generated />
using System;
using BikeRental.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikeRental.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409041408_AddContactNumberToBike")]
    partial class AddContactNumberToBike
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikeRental.Models.Bike", b =>
                {
                    b.Property<int>("BikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BikeId"));

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentRentalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BikeId");

                    b.HasIndex("CurrentRentalId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Bikes", (string)null);

                    b.HasData(
                        new
                        {
                            BikeId = 1,
                            CreatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 833, DateTimeKind.Utc).AddTicks(201),
                            DailyRate = 35.00m,
                            HourlyRate = 6.00m,
                            Location = "Central Station",
                            Model = "Trek Marlin 7",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 833, DateTimeKind.Utc).AddTicks(332)
                        },
                        new
                        {
                            BikeId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 833, DateTimeKind.Utc).AddTicks(452),
                            DailyRate = 28.00m,
                            HourlyRate = 5.00m,
                            Location = "City Park",
                            Model = "Giant Escape 3",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 833, DateTimeKind.Utc).AddTicks(453)
                        },
                        new
                        {
                            BikeId = 3,
                            CreatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 833, DateTimeKind.Utc).AddTicks(455),
                            DailyRate = 40.00m,
                            HourlyRate = 7.00m,
                            Location = "Harbor Point",
                            Model = "Specialized Sirrus",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 833, DateTimeKind.Utc).AddTicks(455)
                        });
                });

            modelBuilder.Entity("BikeRental.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Wallet");

                    b.Property<int>("RentalId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("BikeRental.Models.RentalSession", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RentalId"));

                    b.Property<int>("BikeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RentalId");

                    b.HasIndex("BikeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("RentalSessions", (string)null);
                });

            modelBuilder.Entity("BikeRental.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("OTP")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("OTPExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("IsVerified");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 832, DateTimeKind.Utc).AddTicks(4320),
                            Email = "admin@bikerental.com",
                            FullName = "System Admin",
                            IsAdmin = true,
                            IsVerified = true,
                            PhoneNumber = "+1234567890",
                            UpdatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 832, DateTimeKind.Utc).AddTicks(4462)
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 832, DateTimeKind.Utc).AddTicks(4584),
                            Email = "john@example.com",
                            FullName = "John Doe",
                            IsAdmin = false,
                            IsVerified = true,
                            PhoneNumber = "+0987654321",
                            UpdatedAt = new DateTime(2026, 4, 9, 4, 14, 7, 832, DateTimeKind.Utc).AddTicks(4585)
                        });
                });

            modelBuilder.Entity("BikeRental.Models.Bike", b =>
                {
                    b.HasOne("BikeRental.Models.RentalSession", "CurrentRental")
                        .WithOne()
                        .HasForeignKey("BikeRental.Models.Bike", "CurrentRentalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentRental");
                });

            modelBuilder.Entity("BikeRental.Models.Payment", b =>
                {
                    b.HasOne("BikeRental.Models.RentalSession", "Rental")
                        .WithOne("Payment")
                        .HasForeignKey("BikeRental.Models.Payment", "RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("BikeRental.Models.RentalSession", b =>
                {
                    b.HasOne("BikeRental.Models.Bike", "Bike")
                        .WithMany("RentalHistory")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeRental.Models.User", "User")
                        .WithMany("RentalSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeRental.Models.Bike", b =>
                {
                    b.Navigation("RentalHistory");
                });

            modelBuilder.Entity("BikeRental.Models.RentalSession", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BikeRental.Models.User", b =>
                {
                    b.Navigation("RentalSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
